-- MySQL Script generated by MySQL Workbench
-- Sat Nov 11 19:00:10 2017
-- Model: New Model    Version: 1.0

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbprojectAWS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbprojectAWS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbprojectAWS` DEFAULT CHARACTER SET latin1 ;
USE `dbprojectAWS` ;

-- -----------------------------------------------------
-- Table `dbprojectAWS`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbprojectAWS`.`categories` (
  `category_id` INT(11) NOT NULL,
  `category_name` VARCHAR(45) NULL DEFAULT 'not_found',
  `shortname` VARCHAR(45) NULL DEFAULT 'not_found',
  `sort_name` VARCHAR(45) NULL DEFAULT 'not_found',
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `dbprojectAWS`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbprojectAWS`.`cities` (
  `city` VARCHAR(45) NOT NULL,
  `city_id` INT(11) NULL DEFAULT -1,
  `country` VARCHAR(15) NULL DEFAULT 'not_found',
  `distance` DECIMAL(10,2) NULL DEFAULT 0.0,
  `latitude` DECIMAL(12,8) NULL DEFAULT 0.0,
  `localized_country_name` VARCHAR(45) NULL DEFAULT 'not_found',
  `longitude` DECIMAL(12,8) NULL DEFAULT 0.0,
  `member_count` INT(11) NULL DEFAULT -1,
  `ranking` INT(11) NULL DEFAULT -1,
  `state` VARCHAR(45) NULL DEFAULT 'not_found',
  `zip` INT(11) NULL DEFAULT -1,
  PRIMARY KEY (`city`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `dbprojectAWS`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbprojectAWS`.`groups` (
  `group_id` INT(11) NOT NULL,
  `category_id` INT(11) NOT NULL,
  `category.name` VARCHAR(45) NULL DEFAULT 'not_found',
  `category.shortname` VARCHAR(45) NULL DEFAULT 'not_found',
  `city` VARCHAR(75) NOT NULL,
  `country` VARCHAR(45) NULL DEFAULT 'not_found',
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `description` LONGTEXT NULL DEFAULT NULL,
  `group_photo.base_url` VARCHAR(200) NULL DEFAULT 'not_found',
  `group_photo.highres_link` VARCHAR(200) NULL DEFAULT 'not_found',
  `group_photo.photo_id` INT(11) NULL DEFAULT -1,
  `group_photo.photo_link` VARCHAR(200) NULL DEFAULT 'not_found',
  `group_photo.thumb_link` VARCHAR(200) NULL DEFAULT 'not_found',
  `group_photo.type` ENUM('event', 'member', 'others') NULL DEFAULT 'others',
  `join_mode` ENUM('open', 'approval', 'closed', 'others') NULL DEFAULT 'others',
  `lat` DECIMAL(12,8) NULL DEFAULT 0.0,
  `link` VARCHAR(450) NULL DEFAULT 'not_found',
  `lon` DECIMAL(12,8) NULL DEFAULT 0.0,
  `members` INT(11) NULL DEFAULT -1,
  `group_name` VARCHAR(150) NULL DEFAULT 'not_found',
  `organizer.member_id` INT(11) NULL DEFAULT -1,
  `organizer.name` VARCHAR(65) NULL DEFAULT 'not_found',
  `organizer.photo.base_url` VARCHAR(200) NULL DEFAULT 'not_found',
  `organizer.photo.highres_link` VARCHAR(200) NULL DEFAULT 'not_found',
  `organizer.photo.photo_id` INT(11) NULL DEFAULT -1,
  `organizer.photo.photo_link` VARCHAR(200) NULL DEFAULT 'not_found',
  `organizer.photo.thumb_link` VARCHAR(200) NULL DEFAULT 'not_found',
  `organizer.photo.type` ENUM('event', 'member', 'others') NULL DEFAULT 'others',
  `rating` DECIMAL(4,2) NULL DEFAULT 0.0,
  `state` VARCHAR(45) NULL DEFAULT 'not_found',
  `timezone` VARCHAR(65) NULL DEFAULT 'not_found',
#  `topics` VARCHAR(5000) NULL DEFAULT 'not_found',
  `urlname` VARCHAR(65) NULL DEFAULT 'not_found',
  `utc_offset` INT(11) NULL DEFAULT 0,
  `visibility` ENUM('members', 'public', 'public_limited', 'others') NULL DEFAULT 'others',
  `who` VARCHAR(85) NULL DEFAULT 'not_found',
  PRIMARY KEY (`group_id`),
  INDEX `fk_groups_categories_idx` (`category_id` ASC),
  CONSTRAINT `fk_groups_cities`
    FOREIGN KEY (`city`)
    REFERENCES `dbprojectAWS`.`cities` (`city`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groups_categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `dbprojectAWS`.`categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbprojectAWS`.`venue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbprojectAWS`.`venues` (
  `venue_id` INT(11) NOT NULL,
  `address_1` VARCHAR(200) NULL DEFAULT 'not_found',
  `address_2` VARCHAR(200) NULL DEFAULT 'not_found',
  `address_3` VARCHAR(200) NULL DEFAULT 'not_found',
  `city` VARCHAR(45) NULL DEFAULT 'not_found',
  `country` VARCHAR(45) NULL DEFAULT 'not_found',
  `distance` DECIMAL(10,2) NULL DEFAULT 0.0,
  `lat` DECIMAL(12,8) NULL DEFAULT 0.0,
  `localized_country_name` VARCHAR(45) NULL DEFAULT 'not_found',
  `lon` DECIMAL(12,8) NULL DEFAULT 0.0,
  `venue_name` VARCHAR(300) NULL DEFAULT 'not_found',
  `phone` BIGINT(20) NULL DEFAULT -1,
  `rating` DECIMAL(5,2) NULL DEFAULT 0.0,
  `rating_count` INT(11) NULL DEFAULT -1,
  `state` VARCHAR(45) NULL DEFAULT 'not_found',
  `zip` INT(11) NULL DEFAULT -1,
  PRIMARY KEY (`venue_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `dbprojectAWS`.`venues_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbprojectAWS`.`venues_groups` (
  `venue_id` INT(11) NOT NULL,
  `group_id` INT(11) NOT NULL,
  PRIMARY KEY (`venue_id`,`group_id`),
  INDEX `fk_venues_groups_idx` (`group_id` ASC),
  CONSTRAINT `fk_venues_groups_venues`
    FOREIGN KEY (`venue_id`)
    REFERENCES `dbprojectAWS`.`venues` (`venue_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venues_groups_groups`
    FOREIGN KEY (`group_id`)
    REFERENCES `dbprojectAWS`.`groups` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `dbprojectAWS`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbprojectAWS`.`events` (
  `event_id` VARCHAR(75) NOT NULL,
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `description` LONGTEXT NULL DEFAULT NULL,
  `duration` INT(11) NULL DEFAULT 10800,
  `event_url` VARCHAR(300) NULL DEFAULT 'not_found',
 # `fee.accepts` ENUM('paypal', 'amazon', 'wepay', 'cash', 'others') NULL DEFAULT 'others',
 # `fee.amount` DECIMAL(13,2) NULL DEFAULT 0.0,
 # `fee.currency` VARCHAR(15) NULL DEFAULT 'not_found',
 # `fee.description` VARCHAR(45) NULL DEFAULT 'per person',
 # `fee.label` VARCHAR(45) NULL DEFAULT 'Price',
 # `fee.required` TINYINT(4) NULL DEFAULT 0,
  `group.created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `group.group_lat` DECIMAL(12,8) NULL DEFAULT 0.0,
  `group.group_lon` DECIMAL(12,8) NULL DEFAULT 0.0,
  `group_id` INT(11) NOT NULL,
  `group.join_mode` ENUM('open', 'approval', 'closed', 'others') NULL DEFAULT 'others',
  `group.name` VARCHAR(70) NULL DEFAULT 'not_found',
  `group.urlname` VARCHAR(90) NULL DEFAULT 'not_found',
  `group.who` VARCHAR(45) NULL DEFAULT 'not_found',
  `headcount` INT(11) NULL DEFAULT -1,
 # `how_to_find_us` VARCHAR(250) NULL DEFAULT 'not_found.',
  `maybe_rsvp_count` INT(11) NULL DEFAULT -1,
  `event_name` VARCHAR(95) NULL DEFAULT 'not_found',
#  `photo_url` VARCHAR(200) NULL DEFAULT 'not_found',
#  `rating.average` DECIMAL(5,2) NULL DEFAULT 0.0,
#  `rating.count` INT(11) NULL DEFAULT -1,
  `rsvp_limit` INT(11) NULL DEFAULT -1,
  `event_status` ENUM('past', 'upcoming', 'others') NULL DEFAULT 'others',
  `event_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `utc_offset` INT(11) NULL DEFAULT -1,
  `venue.address_1` VARCHAR(200) NULL DEFAULT 'not_found',
#  `venue.address_2` VARCHAR(200) NULL DEFAULT 'not_found',
  `venue.city` VARCHAR(45) NULL DEFAULT 'not_found',
  `venue.country` VARCHAR(45) NULL DEFAULT 'not_found',
  `venue_id` INT(11) NOT NULL,
  `venue.lat` DECIMAL(12,8) NULL DEFAULT 0.0,
  `venue.localized_country_name` VARCHAR(45) NULL DEFAULT 'not_found',
  `venue.lon` DECIMAL(11,8) NULL DEFAULT 0.0,
  `venue.name` VARCHAR(300) NULL DEFAULT 'not_found',
  `venue.phone` BIGINT(20) NULL DEFAULT -1,
  `venue.repinned` TINYINT(4) NULL DEFAULT 0,
  `venue.state` VARCHAR(45) NULL DEFAULT 'not_found',
  `venue.zip` INT(11) NULL DEFAULT -1,
  `visibility` ENUM('public', 'public_limited', 'members', 'others') NULL DEFAULT 'others',
  `waitlist_count` INT(11) NULL DEFAULT -1,
#  `why` VARCHAR(500) NULL DEFAULT 'not_found',
  `yes_rsvp_count` INT(11) NULL DEFAULT -1,
  PRIMARY KEY (`event_id`),
  INDEX `fk_events_groups_idx` (`group_id` ASC),
  CONSTRAINT `fk_events_venues`
    FOREIGN KEY (`venue_id`)
    REFERENCES `dbprojectAWS`.`venues` (`venue_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_groups_idx`
    FOREIGN KEY (`group_id`)
    REFERENCES `dbprojectAWS`.`groups` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbprojectAWS`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbprojectAWS`.`members` (
  `member_id` INT(11) NOT NULL,
  `bio` VARCHAR(400) NOT NULL DEFAULT 'not_found',
  `city` VARCHAR(45) NULL DEFAULT 'not_found',
  `country` VARCHAR(45) NULL DEFAULT 'not_found',
  `hometown` VARCHAR(45) NULL DEFAULT 'not_found',
  `joined` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `lat` DECIMAL(12,8) NULL DEFAULT 0.0,
  `link` VARCHAR(200) NULL DEFAULT 'not_found',
  `lon` DECIMAL(12,8) NULL DEFAULT 0.0,
  `member_name` VARCHAR(45) NULL DEFAULT 'not_found',
#  `other_services` VARCHAR(999) NULL DEFAULT 'not_found',
#  `photo` VARCHAR(999) NULL DEFAULT 'not_found',
#  `self` VARCHAR(999) NULL DEFAULT 'not_found',
  `state` VARCHAR(45) NULL DEFAULT 'not_found',
  `member_status` ENUM('active', 'prereg', 'others') NULL DEFAULT 'others',
#  `topics` VARCHAR(5000) NULL DEFAULT 'not_found',
  `visited` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `group_id` INT(11) NOT NULL,
  PRIMARY KEY (`member_id`),
  INDEX `fk_members_groups_idx` (`group_id` ASC),
  CONSTRAINT `fk_members_groups_idx`
    FOREIGN KEY (`group_id`)
    REFERENCES `dbprojectAWS`.`groups` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbprojectAWS`.`groups_topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbprojectAWS`.`groups_topics` (
  `topic_id` INT(11) NOT NULL,
  `topic_key` VARCHAR(60) NULL DEFAULT 'not_found',
  `topic_name` VARCHAR(60) NULL DEFAULT 'not_found',
  `group_id` INT(11) NOT NULL,
  PRIMARY KEY (`topic_id`,`group_id`),
  INDEX `fk_groups_topics_idx` (`group_id` ASC),
  CONSTRAINT `fk_groups_topics_idx`
    FOREIGN KEY (`group_id`)
    REFERENCES `dbprojectAWS`.`groups` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbprojectAWS`.`members_topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbprojectAWS`.`members_topics` (
  `topic_id` INT(11) NOT NULL,
  `topic_key` VARCHAR(99) NULL DEFAULT 'not_found',
  `topic_name` VARCHAR(99) NULL DEFAULT 'not_found',
  `member_id` INT(11) NOT NULL,
  PRIMARY KEY (`topic_id`,`member_id`),
  INDEX `fk_members_topics_idx` (`member_id` ASC),
  CONSTRAINT `fk_members_topics_idx`
    FOREIGN KEY (`member_id`)
    REFERENCES `dbprojectAWS`.`members` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbprojectAWS`.`main_topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbprojectAWS`.`main_topics` (
  `main_topic_id` INT(11) NOT NULL,
  `topic_name` VARCHAR(99) NULL DEFAULT 'not_found',
  `topic_key` VARCHAR(99) NULL DEFAULT 'not_found',
  `shortname` VARCHAR(99) NULL DEFAULT 'not_found',
  `sort_name` VARCHAR(99) NULL DEFAULT 'not_found',
  `icon` VARCHAR(499) NULL DEFAULT 'not_found',
  `photo` VARCHAR(499) NULL DEFAULT 'not_found',
  `category_id` INT(11) NOT NULL,
  PRIMARY KEY (`main_topic_id`,`category_id`),
  INDEX `fk_category_main_topics_idx` (`category_id` ASC),
  CONSTRAINT `fk_category_main_topics_idx`
    FOREIGN KEY (`category_id`)
    REFERENCES `dbprojectAWS`.`categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `dbprojectAWS`.`sub_topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbprojectAWS`.`sub_topics` (
  `sub_topic_id` INT(11) NOT NULL,
  `description` VARCHAR(499) NULL DEFAULT 'not_found',
  `link` VARCHAR(99) NULL DEFAULT 'not_found',
  `members` INT(11) NULL DEFAULT -1,
  `sub_topic_name` VARCHAR(99) NULL DEFAULT 'not_found',
  `updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `urlkey` VARCHAR(99) NULL DEFAULT 'not_found',
  `main_topic_id` INT(11) NOT NULL,
  PRIMARY KEY (`sub_topic_id`),
  INDEX `fk_sub_topic_main_topics_idx` (`main_topic_id` ASC),
  CONSTRAINT `fk_sub_topic_main_topics_idx`
    FOREIGN KEY (`main_topic_id`)
    REFERENCES `dbprojectAWS`.`main_topics` (`main_topic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
